### PR TITLE
Root folder detection

### PR DESCRIPTION
**Pull request by psyomn**
Hey! Not quite sure how much you'd be interested for these changes. The idea is very simple: it can execute `cargo readme` from anywhere in the project, and will be able to locate the relative root.

If you're interested in these changes just let me know and I'll tidy up my contributions.

Cheers!

### CODE REVIEW

**Comment by livioribeiro** [comment]
That would be great!

But you should take a look at the doc comments on `main.rs`, since `cargo-readme` by default prepends the crate name to the output and indent the headings ('#' becomes '##' and so on) you should fix that when copying `README.md` into `main.rs`.

BTW, do you think the `-o --output` should be relative to root directory too?

**Comment by psyomn** [comment]
Woops! Didn't notice that, thanks for letting me know (about the doc comments)!

`-o --output`, would probably be good to point to other paths as well (so I think this shouldn't be relative to current project directory). For example if we had a bunch of rust projects and wanted to iterate through each and export to some abs path, relativity might hurt us.

I'm going to clean up some of my additions, and ping you back when I think it's ready!

Thanks!

**Comment by psyomn** [comment]
Well, I made `execute` return `Result`. I'm not sure if you agree with this; if you don't I can just revert these changes. Other than that, let me know if there's anything else you don't like and I'll fix it; else I think this might be ready to be merged. Was fun working on this feature!

**Comment by livioribeiro** [comment]
I made the `execute` function just to separate the program execution from the `clap` stuff, so I don't think it is worth it making it return `Result`.

You're using `#[feature(path_ext)]`, is there a way to do it in stable until 1.5 arrives? (PathExt will be stable in 1.5)

In `main.rs` where it goes

```
//! ```
//! Your crate's badges here
//!
//! {{readme}}
//!
//! Some additional info here
//! ```
```

You could change to

```
//! ```markdown
//! Your crate's badges here
//!
//! {{readme}}
//!
//! Some additional info here
//! ```
```

So it does not get rendered as a  `rust` code block.

After that, I think it will be ready to merge.

And thanks! I'm glad to hear that you had fun coding this feature!

**Comment by psyomn** [comment]
Woops! Missed the `rust`/`markdown` label. So yes, in the above commits, I scrapped the `path_ext`, and used currently available fns. I bundled the use stuff in the function as well so it's easier to trace what needs refactoring in the future!

I ran it against some places and it seems to be working OK. Let me know if you want any other changes!

**Comment by psyomn** [comment]
I put `Cargo.lock` back as well, as I misunderstood what the guidelines said [here](http://doc.crates.io/guide.html#cargotoml-vs-cargolock). Sorry about that!

**Comment by livioribeiro** [comment]
Thanks!

**Pull request merged**
